#! /bin/bash


action="$1"
addr="$2"

PATH=/bin:/sbin:/usr/bin:/usr/sbin

case "${action}" in
    add | update )
        ip neigh replace proxy "${addr}" dev tun0
        ;;
    delete )
        ip neigh del proxy "${addr}" dev tun0
        ;;
esac

exit $?
