---
# tasks file for base-commands
- name: "Enable EPEL repository"
  command: "amazon-linux-extras install epel -y"
  args:
    creates: /etc/yum.repos.d/epel.repo

- name: "Install base utility programs"
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
