---
# tasks file for openvpn-server
- name: "Ensure PKI is initialized"
  ansible.builtin.include_tasks: "pki.yml"

- name: "Generate client configuration file"
  ansible.builtin.include_tasks: "client.yml"

- name: "Enable IP forwarding"
  ansible.builtin.include_tasks: "forward.yml"

- name: "Install OpenVPN"
  ansible.builtin.package:
    name:
      - openvpn
      - easy-rsa
    state: present

- name: "Ensure {{ openvpn.key | dirname }} exists"
  ansible.builtin.file:
    path: "{{ openvpn.key | dirname }}"
    state: directory
    mode: '0711'
    owner: root
    group: root

- name: "Generate DH parameters"
  community.crypto.openssl_dhparam:
    path: "{{ pki.path }}/dh.pem"
    size: 4096
  delegate_to: localhost
  become: false

- name: "Generate TLS auth key"
  ansible.builtin.command: "openvpn --genkey secret {{ pki.path }}/ta.key"
  args:
    creates: "{{ pki.path }}/ta.key"
  delegate_to: localhost
  become: false

- name: "Creates the CSR from EasyRSA PKI"
  command:
    argv:
      - "easyrsa"
      - "--batch"
      - "--pki-dir={{ pki.path }}"
      - "--req-cn={{ inventory_hostname }}"
      - "gen-req"
      - "{{ inventory_hostname }}"
      - "nopass"
    creates: "{{ pki.path }}/reqs/{{ inventory_hostname }}.req"
  delegate_to: localhost
  become: false

- name: "Sign the CSR"
  command:
    argv:
      - "easyrsa"
      - "--batch"
      - "--pki-dir={{ pki.path }}"
      - "--subject-alt-name={{ (san.dns + san.ipv4 + san.ipv6) | join(',') }}"
      - "sign-req"
      - "server"
      - "{{ inventory_hostname }}"
    creates: "{{ pki.path }}/issued/{{ inventory_hostname }}.crt"
  delegate_to: localhost
  become: false
  vars:
    san:
      dns:
        - "DNS:{{ inventory_hostname }}"
      ipv4: "{{ ansible_facts.all_ipv4_addresses | ansible.netcommon.ipaddr('public') | map('regex_replace', '^', 'IP:') | list }}"
      ipv6: "{{ ansible_facts.all_ipv6_addresses | ansible.netcommon.ipaddr('public') | map('regex_replace', '^', 'IP:') | list }}"

- name: "Import CA"
  ansible.builtin.copy:
    src: "{{ pki.path }}/ca.crt"
    dest: "{{ openvpn.ca }}"
    mode: '0644'
    owner: root
    group: root
  notify:
    - restart openvpn

- name: "Import OpenVPN Certificate"
  ansible.builtin.copy:
    src: "{{ pki.path }}/issued/{{ inventory_hostname }}.crt"
    dest: "{{ openvpn.cert }}"
    mode: '0644'
    owner: root
    group: root
  notify:
    - restart openvpn

- name: "Import OpenVPN Certificate key"
  ansible.builtin.copy:
    src: "{{ pki.path }}/private/{{ inventory_hostname }}.key"
    dest: "{{ openvpn.key }}"
    mode: '0600'
    owner: root
    group: root
  notify:
    - restart openvpn

- name: "Import TLS auth key"
  ansible.builtin.copy:
    src: "{{ pki.path }}/ta.key"
    dest: "{{ openvpn.ta }}"
    mode: '0600'
    owner: root
    group: root
  notify:
    - restart openvpn

- name: "Import DH parameters"
  ansible.builtin.copy:
    src: "{{ pki.path }}/dh.pem"
    dest: "{{ openvpn.dh }}"
    mode: '0600'
    owner: root
    group: root
  notify:
    - restart openvpn

- name: "Configure OpenVPN server"
  ansible.builtin.template:
    dest: /etc/openvpn/server/server.conf
    src: openvpn.conf.j2
    owner: root
    group: root
    mode: '0600'
  vars:
    server_ipv6: "{{ ansible_facts.all_ipv6_addresses | ansible.netcommon.ipaddr('public') | first | ansible.netcommon.ipsubnet(64) }}"

  notify:
    - restart openvpn
